export const techIcons = [
	{
		key: 1,
		src: "/techs/ts.svg",
		alt: "TypeScript",
		docUrl: "https://www.typescriptlang.org",
	},
	{
		key: 2,
		src: "/techs/js.svg",
		alt: "JavaScript",
		docUrl: "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript",
	},
	{
		key: 3,
		src: "/techs/jamstack.svg",
		alt: "Jamstack",
		docUrl: "https://jamstack.org/",
	},
	{
		key: 4,
		src: "/techs/nextjs.svg",
		alt: "Nextjs",
		docUrl: "https://nextjs.org/",
	},
	{
		key: 5,
		src: "/techs/mongodb.svg",
		alt: "mongodb",
		docUrl: "https://www.mongodb.com",
	},
	{
		key: 6,
		src: "/techs/jest.svg",
		alt: "Jest",
		docUrl: "https://jestjs.io/pt-BR",
	},
	{
		key: 7,
		src: "/techs/chakra.svg",
		alt: "Chakra UI",
		docUrl: "https://chakra-ui.com",
	},
	{
		key: 8,
		src: "/techs/framer-motion.svg",
		alt: "Framer Motion",
		docUrl: "https://www.framer.com/motion",
	},
	{
		key: 9,
		src: "/techs/figma.svg",
		alt: "Figma",
		docUrl: "https://www.figma.com",
	},
	{
		key: 10,
		src: "/techs/styled.svg",
		alt: "Styled Components",
		docUrl: "https://styled-components.com",
	},
	{
		key: 11,
		src: "/techs/tailwind.svg",
		alt: "Tailwind css",
		docUrl: "https://tailwindcss.com",
	},
	{
		key: 12,
		src: "/techs/sass.svg",
		alt: "Sass",
		docUrl: "https://sass-lang.com",
	},
	{
		key: 13,
		src: "/techs/ts.svg",
		alt: "TypeScript",
		docUrl: "https://www.typescriptlang.org",
	},
	{
		key: 14,
		src: "/techs/js.svg",
		alt: "JavaScript",
		docUrl: "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript",
	},
	{
		key: 15,
		src: "/techs/jamstack.svg",
		alt: "Jamstack",
		docUrl: "https://jamstack.org/",
	},
	{
		key: 16,
		src: "/techs/nextjs.svg",
		alt: "Nextjs",
		docUrl: "https://nextjs.org/",
	},
	{
		key: 17,
		src: "/techs/mongodb.svg",
		alt: "mongodb",
		docUrl: "https://www.mongodb.com",
	},
	{
		key: 18,
		src: "/techs/jest.svg",
		alt: "Jest",
		docUrl: "https://jestjs.io/pt-BR",
	},
	{
		key: 19,
		src: "/techs/chakra.svg",
		alt: "Chakra UI",
		docUrl: "https://chakra-ui.com",
	},
	{
		key: 20,
		src: "/techs/framer-motion.svg",
		alt: "Framer Motion",
		docUrl: "https://www.framer.com/motion",
	},
	{
		key: 21,
		src: "/techs/figma.svg",
		alt: "Figma",
		docUrl: "https://www.figma.com",
	},
	{
		key: 22,
		src: "/techs/styled.svg",
		alt: "Styled Components",
		docUrl: "https://styled-components.com",
	},
	{
		key: 23,
		src: "/techs/tailwind.svg",
		alt: "Tailwind css",
		docUrl: "https://tailwindcss.com",
	},
	{
		key: 24,
		src: "/techs/sass.svg",
		alt: "Sass",
		docUrl: "https://sass-lang.com",
	},
];
